Before calling `gdb`, make sure setting `PYTHON_PATH` correctly.
When calling `gdb`, use `gdb --args`